In [20]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
def userinput(x,y,i):
    L=[]
    print("matrix ",i+1)
    for j in range(x):
        l=[]
        print(j+1,"row")
        for k in range(y):
            a=int(input("enter the element "))
            l.append(a)
        L.append(l)
    L =np.array(L)
    return L
def addmax(x,y,n):
    sum=np.zeros((x,y),)
    for i in range(n):
        sum=np.add(sum,userinput(x,y,i))
    return sum

n = int(input("enter the no of matrices to be added (note: must be of same size or order)"))
x= int(input("enter the no of rows"))
y= int(input("enter the no of columns"))
s = addmax(x,y,n)
print(s," is the sum of the matrices")
    
    

enter the no of matrices to be added (note: must be of same size or order)2
enter the no of rows2
enter the no of columns3
matrix  1
1 row
enter the element 1
enter the element 2
enter the element 3
2 row
enter the element 4
enter the element 5
enter the element 6
matrix  2
1 row
enter the element 7
enter the element 8
enter the element 9
2 row
enter the element 1
enter the element 2
enter the element 3
[[ 8. 10. 12.]
 [ 5.  7.  9.]]  is the sum of the matrices


In [8]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np
def userinput(x,y,i):
    try:
        L=[]
        print("matrix ",i)
        for j in range(x):
            l=[]
            print(j+1,"row")
            for k in range(y):
                a=int(input("enter the element "))
                l.append(a)
            L.append(l)
        L =np.array(L)
    return L
    except Exception as E:
        print(E)
def multimax(n):
    try:
        result=1
        for i in range(1,n+1):
            x= int(input("enter the no of rows of matrix"))
            y = int(input("enter the no of columns of matrix"))
            result = np.dot(result,userinput(x,y,i))
        return result
    except Exception as E:
        print(E)
n = int(input("enter the no of matrices"))
r = multimax(n)
print(r)
    

enter the no of matrices2
enter the no of rows of matrix2
enter the no of columns of matrix2
matrix  1
1 row
enter the element 2
enter the element 2
2 row
enter the element 2
enter the element 2
enter the no of rows of matrix2
enter the no of columns of matrix2
matrix  2
1 row
enter the element 2
enter the element 2
2 row
enter the element 2
enter the element 2
[[8 8]
 [8 8]]


In [12]:

#4. Write a Python Program to Sort Words in Alphabetic Order?

a = input("enter the string ")
words = a.split()
words.sort()
for i in words:
    print(i)

enter the string my name is sireesha matta and i live at machilipatnam
and
at
i
is
live
machilipatnam
matta
my
name
sireesha


In [33]:
#5. Write a Python Program to Remove Punctuation From a String
a= input(" enter the string ")
spl = ['~','`','!','@','#','$','%','^','&','*','(',')','-','?','_','+','=','{','}','[',']','|','/',]
for i in spl:
    if i in a:
        a= a.replace(i,"")
        
print(a)

 enter the string enter the stringoh my god!!! you?? python$ rockzz***
enter the stringoh my god you python rockzz


In [ ]:
#2. Write a Python Program to Multiply Two Matrices?
#3. Write a Python Program to Transpose a Matrix?
#4. Write a Python Program to Sort Words in Alphabetic Order?
#5. Write a Python Program to Remove Punctuation From a String?

In [5]:
#3. Write a Python Program to Transpose a Matrix?
import numpy as np
A=np.arange(1,10).reshape((3,3))
print(A)
B=A.transpose(1,0)
print(B)
C=A.transpose(0,1)
print(C)
A.T


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])