In [15]:
#1. Write a Python Program to find sum of array?
import numpy as np
l=[]
n= int(input("enter the no of elements "))
for i in range(n):
    i=int(input("enter the element "))
    l.append(i)

my_arr=np.array(l)
print("the sum of all the elements of array is",my_arr.sum())   

enter the no of elements 5
enter the element 1
enter the element 2
enter the element 3
enter the element 4
enter the element 5
the sum of all the elements of array is 15


In [8]:
#2. Write a Python Program to find largest element in an array?
import numpy as np
l=[]
L=0

n= int(input("enter the no of elements "))
for i in range(n):
    i=int(input("enter the element "))
    l.append(i)
my_arr=np.array(l)

#using for loop    
for i in my_arr:    
    if(L<=i):
        L=i
print("largest element in the array is ",L)

#using numpy methods
maximum=my_arr.max()
print("largest element in the array is ",maximum)

enter the no of elements 5
enter the element 1
enter the element 2
enter the element 3
enter the element 4
enter the element 6
largest element in the array is  6
largest element in the array is  6


In [70]:
#3. Write a Python Program for array rotation?
import numpy as np

def rotate(arr,x,y):
    T=np.zeros((y,x),"int")
    print(arr)
    for i in range(x):
        for j in range(y,-1):
            T[i][j]=(arr[j][i])
    return(T)

            
            
L=[]
x= int(input("enter the size of array no of rows "))
y= int(input("enter the no of columns"))
for i in range(x):
    l=[]
    for j in range(y):
        a=int(input("enter the element in  row and  column of the array "))
        l.append(a)
    L.append(l)
#print(L)
my_arr=np.array([L])
#print(my_arr)
rotate(my_arr,x,y)

enter the size of array no of rows 3
enter the no of columns3
enter the element in  row and  column of the array 1
enter the element in  row and  column of the array 2
enter the element in  row and  column of the array 3
enter the element in  row and  column of the array 4
enter the element in  row and  column of the array 5
enter the element in  row and  column of the array 6
enter the element in  row and  column of the array 7
enter the element in  row and  column of the array 8
enter the element in  row and  column of the array 9
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:

#5. Write a Python Program to check if given array is Monotonic?

def isMonotonic(A):
    return(all(A[i]<=A[i+1] for i in range(len(A)-1)) or all(a[i]>=A[i+1] for i in range(len(A)-1)))
A=[1,2,3,4,5,6]
print(isMonotonic(A))

True


In [25]:
#4. Write a Python Program to Split the array and add the first part to the end


import numpy as np
row=int(input("no of rows "))
col=int(input("no of columns "))
v=[[int(input("element ")) for i in range(col)]for j in range(row)]
arr=np.array(v)
print(arr.size)
print(arr.dtype)
print(arr)
n=int(input("how do you like to split the 2d array "))
S=np.array_split(arr,n,0)
print("the array splitted into ",S)
#np.delete(arr,1,1)
p=S.pop(0)
S.append(p)
newarr=np.array(S)
print("new array after splitting and adding",newarr)
print(newarr.size)
print(newarr.dtype)

no of rows 3
no of columns 2
element 2
element 5
element 8
element 9
element 6
element 5
6
int32
[[2 5]
 [8 9]
 [6 5]]
how do you like to split the 2d array 3
the array splitted into  [array([[2, 5]]), array([[8, 9]]), array([[6, 5]])]
new array after splitting and adding [[[8 9]]

 [[6 5]]

 [[2 5]]]
6
int32


In [53]:
A=[[1,2,3],[4,5,6],[7,8,9]]
Arr=np.array(A)
print(Arr)
print(Arr.dtype)
temp = Arr[:,2]
swapped =np.swapaxes(Arr,0,1)
swapped

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])